---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: users-service-ns
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: acrneudevall.azurecr.io/users-service:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users-service-ns  
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

