name: Build and Deploy

on:
  push:
    branches:
      - dev

env:
  APP_NAME: ${{ github.event.repository.name }}
  NAMESPACE: ${APP_NAME}-ns
  ACR_REGISTRY: acrneudevall.azurecr.io
  ACR_IMAGE_TAG: dev-${{ github.run_number }}
  ACR_IMAGE_NAME: ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Get AKS credentials
        run: az aks get-credentials --name aksneudev --resource-group rg-neu-dev

      - name: Create namespace if it doesn't exist
        run: |
          if !kubectl get namespace $NAMESPACE &> /dev null; then
            echo "Namespace $NAMESPACE does not exist, creating it."
            kubectl create namespace $NAMESPACE
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          tags: |
            ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:dev
            ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}:${{ env.ACR_IMAGE_TAG }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml